name: fluq
description: A simple state management api based on streams with query and mutation handlers
version: 0.0.1
repository: https://github.com/mceck/fluq
homepage:

environment:
  sdk: '>=2.7.0 <3.0.0'
  flutter: '>=1.17.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^5.0.0
  rxdart: ^0.26.0

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
